# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb",
         "Deck": "00_card.ipynb",
         "Hand": "00_card.ipynb",
         "find_defining_class": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://fs2013.github.io/hesap/"

git_url = "https://github.com/fs2013/hesap/tree/master/"

def custom_doc_links(name): return None
