# AUTOGENERATED! DO NOT EDIT! File to edit: 03_config.ipynb (unless otherwise specified).

__all__ = ['get_config']

# Cell

"""This module contains a simple method to access personal secret config
parameters that are stored in .yml file
by faf
Copyright 2021 Fafs
License: http://creativecommons.org/licenses/by/4.0/
"""

import yaml


def get_config(config_filename: str):
    """
    Get config parameters in a dict using yaml
    """
    with open(config_filename, "r") as ymlfile:
        cfg = yaml.load(ymlfile, Loader=yaml.SafeLoader)
    return cfg